### PR TITLE
Fix usages section of the parse method

### PR DESCRIPTION
**Pull request by zero323**
Current example generates:

```python
>>> parse('struct[a:struct[a:string]]').simpleString()
Traceback (most recent call last):
...
UnsupportedDataType: Unsupported type struct[a:string]] for field struct[a
```

### CODE REVIEW

**Comment by skliarpawlo** [comment]
Hey @zero323 you are welcome to make cross-repo pull-request to contribute! Thanks for noting this!

**Comment by zero323** [comment]
@skliarpawlo Changed to master.

**Comment by skliarpawlo** [comment]
@zero323 looks like this is a PR to your repo master, you should create a cross repo PR instead. I think so because I have to options to merge your contribution

**Comment by zero323** [comment]
@skliarpawlo Facepalm.

**Pull request merged**
